version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_gabrielverao
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_gabrielverao
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - ./rabbitmq_config/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq_config/definitions.json:/etc/rabbitmq/definitions.json
    command: rabbitmq-server

  mongo:
    image: mongo:6
    container_name: mongo_gabrielverao
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
  rabbitmqdata:
